# Generated by Django 4.1.5 on 2023-02-13 17:16

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesetting_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
