# Generated by Django 4.1.5 on 2023-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
