# Generated by Django 4.1.5 on 2023-02-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های با ما'},
        ),
    ]
